language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.xml

after_script:
  - bash <(curl -s https://codecov.io/bash)
